name: Release to PyPI

on:
  push:
    tags:
        - 'v0.[0-9]+.[0-9]+'

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-22.04
    environment:
        name: deploy-to-pypi
        url: https://pypi.org/project/ropt/
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name}}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
    - name: Build and deploy
      run: uv build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1

  deploy-docs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name}}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
    - name: Initialize deployment
      id: docs
      run: |
        uv sync --all-extras --dev
        echo "MAJOR=$(uv run python -c 'from ropt import version; print(version.version_tuple[0])')" >> $GITHUB_OUTPUT
        echo "MINOR=$(uv run python -c 'from ropt import version; print(version.version_tuple[1])')" >> $GITHUB_OUTPUT
    - name: Deploy
      env:
        MAJOR: ${{ steps.docs.outputs.MAJOR }}
        MINOR: ${{ steps.docs.outputs.MINOR }}
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git fetch origin gh-pages --depth=1
        uv run mike deploy $MAJOR.$MINOR latest --update-aliases --push
